### ISSUE TITLE
Failed config

### ISSUE THREAD

**Issue by KoKolaj** [Chreece/LD2411S-ESPHome#1]
Failed config

esp32: None
  
  Please specify flash_size within esp32 configuration only.
  board: firebeetle32
  framework: 
    version: 2.0.5
    source: ~3.20005.0
    platform_version: platformio/espressif32@5.4.0
    type: arduino
  flash_size: 4MB
  variant: ESP32

**Comment by Chreece** [comment]
This is an example configuration for firebeetle32 boards, you should change it to match your config if you are using another board.

**Comment by KoKolaj** [comment]
> This is an example configuration for firebeetle32 boards, you should change it to match your config if you are using another board.

It worked, but today the Esphome update to the "Esphome 2023.11.0" version can no longer be updated.
Unfortunately I don't know how to edit yaml
