### ISSUE TITLE
Protocol decoding

### ISSUE THREAD

**Issue by GrumpyMeow** [Chreece/LD2411S-ESPHome#3]
Hi Chreece,
I'm tinkering with my LD2411-S device using your code. It seems to work correctly and is as-is usable for me.

I'm looking into your code and trying to match it with some datasheets i found.
Can it be that you did a "minimal" implementation of the protocol? Where did you base your protocol implementation on?

If i look at the [datasheet](https://drive.google.com/drive/folders/16zI-fium_BZeP08EyQke0rWp0BJTMvw3) i found, i see that in your code you only parse a small part of the frame. Am i correct in this?

I wanted to see if i was able to enable "Engineering mode" ..

**Comment by Chreece** [comment]
The Datasheet you posted is about LD-2410, the docs about LD2411-S are included in this repo
